### ISSUE TITLE
support for SW_VERSION 70

### ISSUE THREAD

**Issue by mcsitter** [openneuropet/PET2BIDS#218]
**Describe the bug**
I want to use this tool to convert some FDG PET data. Sadly there are files with "sw_version" equal to 70. Since this is not in the `ecat_headers.json` the `confirmed_version` in the `read_ecat` function does not become true, and the Exception is raised. Can we start supporting SW_VERSION 70? Since this is part of the reading of the ECAT data, which makes sense due to the structure of fixed bytes for the header data of the ECAT files, I would alternatively need to figure out how to circumvent it.
My dataset contains files with supported versions, so everything else appears OK.

`nibabel.ecat.load` can read the file and appears to have the correct data in the header, but I couldn't figure out how exactly that works. It appears to me as if they ignore the version. I think they just use this one definition for the structure of the mainheader [here](https://github.com/nipy/nibabel/blob/8fea2a8e50aaf4d8b0d4bfff7a21b132914120ee/nibabel/ecat.py#L58).

**To Reproduce**
1. `pypet2bids.ecat.Ecat(path_to_ecat)`
2. `Exception: Unable to determine ECAT File Type from these types dict_keys(['63', '72', '73'])`

**Expected behavior**
The file should be loaded just like the others.

**Desktop:**
 - Ubuntu 22.04.2 LTS
 - Python 3.10.6

Thank you in advance for any help.

**Comment by bendhouseart** [comment]
@mcsitter 7.0 isn't listed in the supported versions is because we've never been able to come across any of them or [documentation](https://github.com/openneuropet/PET2BIDS/tree/main/ecat_validation/ecat_info) that adequately defines their headers.

Defined (as far as pet2bids is concerned) ecat versions are listed in [pypet2bids/pypet2bids/ecat_headers.json](https://github.com/openneuropet/PET2BIDS/blob/main/pypet2bids/pypet2bids/ecat_headers.json#L14), see the below example:

```json
  "ecat_headers": {
        "63": {
            "mainheader": [
                {
                    "byte": 0,
                    "variable_name": "%FILL(14)",
                    "type": "Integer*2",
                    "comment": "User reserved space (28 bytes)",
                    "struct": "14H"
                }
```

You're erroring out simply because there is no entry for 70. In the meantime I've gone ahead and created a 70 entry in `ecat_headers.json` in a new PR aptly titled [ 218-support-for-sw_version-70](https://github.com/openneuropet/PET2BIDS/pull/220). You can either pull and install pet2bids from that branch or simply place the ecat_headers.json attached in this comment into your current install of pypet2bids next to `ecat.py`.
[ecat_headers.json.zip](https://github.com/openneuropet/PET2BIDS/files/12439138/ecat_headers.json.zip)

If you go the later route you'll need to unzip the file as github doesn't seem to like attaching json files here in the comments..

If you're able to share the source data or a phantom from your ECAT 7 scanner we'd be more than happy to test and integrate it into our codebase.

Let me know if there's any additional help you require in the meantime.

**Comment by CPernet** [comment]
+1 we need at least a phantom to be able to state that we support such version, ideally have the documentation but it is unlikely as this seems lost to everyone.

**Comment by KeithGeorgeCiantar** [comment]
I ran into this issue earlier today when I was using pypet2bids.ecat2nii.ecat2nii to convert some FET PET data. Just like @mcsitter I got the error `Exception: Unable to determine ECAT File Type from these types dict_keys(['63', '72', '73'])`.

Following the suggested fix I placed the updated JSON into the pypet2bids folder and the issue was resolved.

I cannot give you the data I am working with, but I wanted to thank you for making the fix available!

Since @CPernet mentioned needing a phantom to properly support this format, I will try to ask around and see if we can figure something out.

**Comment by CPernet** [comment]
The ecat reader should be able to read 7+ so once you uploaded the phantom we'll start testing.
Be also aware of issue https://github.com/openneuropet/PET2BIDS/issues/272 is you have negative values (back rejection), we still have an issue with the python version ..

**Comment by bendhouseart** [comment]
Following @KeithGeorgeCiantar 's feedback I'm going to close the pr that "adds support" for ecat 7.0 so that a user need not manually perform the steps he did to verify.
